<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<databrowser>
<xyGraphSettings>
    <axisSettingsList>
        <autoFormat>true</autoFormat>
        <autoScale>false</autoScale>
        <autoScaleThreshold>0.01</autoScaleThreshold>
        <dashGridLine>true</dashGridLine>
        <dateEnabled>true</dateEnabled>
        <foregroundColor>
            <blue>0</blue>
            <green>0</green>
            <red>0</red>
        </foregroundColor>
        <formatPattern>MM-dd</formatPattern>
        <logScale>false</logScale>
        <majorGridColor>
            <blue>200</blue>
            <green>200</green>
            <red>200</red>
        </majorGridColor>
        <onPrimarySide>true</onPrimarySide>
        <range>
            <lower>1.424731404391E12</lower>
            <upper>1.426840169964E12</upper>
        </range>
        <scaleFont>1|Cantarell|11.0|0|GTK|1|</scaleFont>
        <showMajorGrid>false</showMajorGrid>
        <title>Time</title>
        <titleFont>1|Cantarell|11.0|1|GTK|1|</titleFont>
    </axisSettingsList>
    <axisSettingsList>
        <autoFormat>true</autoFormat>
        <autoScale>false</autoScale>
        <autoScaleThreshold>0.1</autoScaleThreshold>
        <dashGridLine>true</dashGridLine>
        <dateEnabled>false</dateEnabled>
        <foregroundColor>
            <blue>196</blue>
            <green>21</green>
            <red>21</red>
        </foregroundColor>
        <formatPattern>############.##</formatPattern>
        <logScale>false</logScale>
        <majorGridColor>
            <blue>200</blue>
            <green>200</green>
            <red>200</red>
        </majorGridColor>
        <onPrimarySide>true</onPrimarySide>
        <range>
            <lower>-0.29500000000000004</lower>
            <upper>3.245</upper>
        </range>
        <scaleFont>1|Cantarell|11.0|0|GTK|1|</scaleFont>
        <showMajorGrid>false</showMajorGrid>
        <title>CB:MWPC:HV:CH1:Imon:RBV</title>
        <titleFont>1|Cantarell|11.0|1|GTK|1|</titleFont>
    </axisSettingsList>
    <plotAreaBackColor>
        <blue>255</blue>
        <green>255</green>
        <red>255</red>
    </plotAreaBackColor>
    <showLegend>true</showLegend>
    <showPlotAreaBorder>false</showPlotAreaBorder>
    <showTitle>true</showTitle>
    <title></title>
    <titleColor>
        <blue>0</blue>
        <green>0</green>
        <red>0</red>
    </titleColor>
    <titleFont>1|Cantarell|12.0|1|GTK|1|</titleFont>
    <traceSettingsList>
        <antiAliasing>true</antiAliasing>
        <areaAlpha>100</areaAlpha>
        <baseLine>ZERO</baseLine>
        <drawYErrorInArea>true</drawYErrorInArea>
        <errorBarCapWidth>4</errorBarCapWidth>
        <errorBarColor>
            <blue>196</blue>
            <green>21</green>
            <red>21</red>
        </errorBarColor>
        <errorBarEnabled>true</errorBarEnabled>
        <lineWidth>2</lineWidth>
        <name>CB:MWPC:HV:CH1:Imon:RBV</name>
        <pointSize>4</pointSize>
        <pointStyle>NONE</pointStyle>
        <traceColor>
            <blue>196</blue>
            <green>21</green>
            <red>21</red>
        </traceColor>
        <traceType>STEP_HORIZONTALLY</traceType>
        <xAxis>0</xAxis>
        <xErrorBarType>BOTH</xErrorBarType>
        <yAxis>0</yAxis>
        <yErrorBarType>BOTH</yErrorBarType>
    </traceSettingsList>
    <transparent>false</transparent>
</xyGraphSettings>
    <scroll>false</scroll>
    <update_period>3.0</update_period>
    <start>2015/02/23 23:43:24.391</start>
    <end>2015/03/20 09:29:29.964</end>
    <archive_rescale>STAGGER</archive_rescale>
    <pvlist>
        <pv>
            <name>CB:MWPC:HV:CH1:Imon:RBV</name>
            <visible>true</visible>
            <axis>0</axis>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
            <archive>
                <name>rdb</name>
                <url>jdbc:mysql://slowcontrol.office.a2.kph/archive</url>
                <key>1</key>
            </archive>
        </pv>
    </pvlist>
</databrowser>