<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<databrowser>
<xyGraphSettings>
    <axisSettingsList>
        <autoFormat>true</autoFormat>
        <autoScale>false</autoScale>
        <autoScaleThreshold>0.01</autoScaleThreshold>
        <dashGridLine>true</dashGridLine>
        <dateEnabled>true</dateEnabled>
        <foregroundColor>
            <blue>0</blue>
            <green>255</green>
            <red>0</red>
        </foregroundColor>
        <formatPattern>HH:mm</formatPattern>
        <logScale>false</logScale>
        <majorGridColor>
            <blue>200</blue>
            <green>200</green>
            <red>200</red>
        </majorGridColor>
        <onPrimarySide>true</onPrimarySide>
        <range>
            <lower>1.547813570924E12</lower>
            <upper>1.547818970924E12</upper>
        </range>
        <scaleFont>1|Cantarell|11.0|0|GTK|1|</scaleFont>
        <showMajorGrid>false</showMajorGrid>
        <title>Time</title>
        <titleFont>1|Cantarell|11.0|1|GTK|1|</titleFont>
    </axisSettingsList>
    <axisSettingsList>
        <autoFormat>true</autoFormat>
        <autoScale>false</autoScale>
        <autoScaleThreshold>0.1</autoScaleThreshold>
        <dashGridLine>true</dashGridLine>
        <dateEnabled>false</dateEnabled>
        <foregroundColor>
            <blue>0</blue>
            <green>255</green>
            <red>0</red>
        </foregroundColor>
        <formatPattern>0.####E0</formatPattern>
        <logScale>false</logScale>
        <majorGridColor>
            <blue>200</blue>
            <green>200</green>
            <red>200</red>
        </majorGridColor>
        <onPrimarySide>true</onPrimarySide>
        <range>
            <lower>17000.0</lower>
            <upper>25000.0</upper>
        </range>
        <scaleFont>1|Cantarell|11.0|0|GTK|1|</scaleFont>
        <showMajorGrid>false</showMajorGrid>
        <title>BEAM:IonChamber</title>
        <titleFont>1|Cantarell|11.0|1|GTK|1|</titleFont>
    </axisSettingsList>
    <axisSettingsList>
        <autoFormat>true</autoFormat>
        <autoScale>false</autoScale>
        <autoScaleThreshold>0.01</autoScaleThreshold>
        <dashGridLine>true</dashGridLine>
        <dateEnabled>false</dateEnabled>
        <foregroundColor>
            <blue>0</blue>
            <green>0</green>
            <red>0</red>
        </foregroundColor>
        <formatPattern>############.##</formatPattern>
        <logScale>false</logScale>
        <majorGridColor>
            <blue>200</blue>
            <green>200</green>
            <red>200</red>
        </majorGridColor>
        <onPrimarySide>true</onPrimarySide>
        <range>
            <lower>30.0</lower>
            <upper>70.0</upper>
        </range>
        <scaleFont>1|Cantarell|11.0|0|GTK|1|</scaleFont>
        <showMajorGrid>false</showMajorGrid>
        <title>TAGG:TAGG:LadderP2Ratio</title>
        <titleFont>1|Cantarell|11.0|1|GTK|1|</titleFont>
    </axisSettingsList>
    <axisSettingsList>
        <autoFormat>true</autoFormat>
        <autoScale>false</autoScale>
        <autoScaleThreshold>0.01</autoScaleThreshold>
        <dashGridLine>true</dashGridLine>
        <dateEnabled>false</dateEnabled>
        <foregroundColor>
            <blue>255</blue>
            <green>0</green>
            <red>0</red>
        </foregroundColor>
        <formatPattern>############.##</formatPattern>
        <logScale>false</logScale>
        <majorGridColor>
            <blue>200</blue>
            <green>200</green>
            <red>200</red>
        </majorGridColor>
        <onPrimarySide>true</onPrimarySide>
        <range>
            <lower>36.40963855421687</lower>
            <upper>43.01204819277108</upper>
        </range>
        <scaleFont>1|Cantarell|11.0|0|GTK|1|</scaleFont>
        <showMajorGrid>false</showMajorGrid>
        <title>BEAM:PhotonCam:CenterX</title>
        <titleFont>1|Cantarell|11.0|1|GTK|1|</titleFont>
    </axisSettingsList>
    <axisSettingsList>
        <autoFormat>true</autoFormat>
        <autoScale>false</autoScale>
        <autoScaleThreshold>0.01</autoScaleThreshold>
        <dashGridLine>true</dashGridLine>
        <dateEnabled>false</dateEnabled>
        <foregroundColor>
            <blue>0</blue>
            <green>0</green>
            <red>255</red>
        </foregroundColor>
        <formatPattern>############.##</formatPattern>
        <logScale>false</logScale>
        <majorGridColor>
            <blue>200</blue>
            <green>200</green>
            <red>200</red>
        </majorGridColor>
        <onPrimarySide>true</onPrimarySide>
        <range>
            <lower>23.936797793583978</lower>
            <upper>38.3669327914066</upper>
        </range>
        <scaleFont>1|Cantarell|11.0|0|GTK|1|</scaleFont>
        <showMajorGrid>false</showMajorGrid>
        <title>BEAM:PhotonCam:CenterY</title>
        <titleFont>1|Cantarell|11.0|1|GTK|1|</titleFont>
    </axisSettingsList>
    <plotAreaBackColor>
        <blue>255</blue>
        <green>255</green>
        <red>255</red>
    </plotAreaBackColor>
    <showLegend>true</showLegend>
    <showPlotAreaBorder>false</showPlotAreaBorder>
    <showTitle>true</showTitle>
    <title></title>
    <titleColor>
        <blue>0</blue>
        <green>0</green>
        <red>0</red>
    </titleColor>
    <titleFont>1|Cantarell|12.0|1|GTK|1|</titleFont>
    <traceSettingsList>
        <antiAliasing>true</antiAliasing>
        <areaAlpha>100</areaAlpha>
        <baseLine>ZERO</baseLine>
        <drawYErrorInArea>true</drawYErrorInArea>
        <errorBarCapWidth>4</errorBarCapWidth>
        <errorBarColor>
            <blue>34</blue>
            <green>234</green>
            <red>47</red>
        </errorBarColor>
        <errorBarEnabled>true</errorBarEnabled>
        <lineWidth>2</lineWidth>
        <name>BEAM:IonChamber</name>
        <pointSize>4</pointSize>
        <pointStyle>NONE</pointStyle>
        <traceColor>
            <blue>34</blue>
            <green>234</green>
            <red>47</red>
        </traceColor>
        <traceType>STEP_HORIZONTALLY</traceType>
        <xAxis>0</xAxis>
        <xErrorBarType>BOTH</xErrorBarType>
        <yAxis>0</yAxis>
        <yErrorBarType>BOTH</yErrorBarType>
    </traceSettingsList>
    <traceSettingsList>
        <antiAliasing>true</antiAliasing>
        <areaAlpha>100</areaAlpha>
        <baseLine>ZERO</baseLine>
        <drawYErrorInArea>true</drawYErrorInArea>
        <errorBarCapWidth>4</errorBarCapWidth>
        <errorBarColor>
            <blue>0</blue>
            <green>0</green>
            <red>0</red>
        </errorBarColor>
        <errorBarEnabled>true</errorBarEnabled>
        <lineWidth>2</lineWidth>
        <name>TAGG:TAGG:LadderP2Ratio</name>
        <pointSize>4</pointSize>
        <pointStyle>NONE</pointStyle>
        <traceColor>
            <blue>0</blue>
            <green>0</green>
            <red>0</red>
        </traceColor>
        <traceType>STEP_HORIZONTALLY</traceType>
        <xAxis>0</xAxis>
        <xErrorBarType>BOTH</xErrorBarType>
        <yAxis>1</yAxis>
        <yErrorBarType>BOTH</yErrorBarType>
    </traceSettingsList>
    <traceSettingsList>
        <antiAliasing>true</antiAliasing>
        <areaAlpha>100</areaAlpha>
        <baseLine>ZERO</baseLine>
        <drawYErrorInArea>true</drawYErrorInArea>
        <errorBarCapWidth>4</errorBarCapWidth>
        <errorBarColor>
            <blue>255</blue>
            <green>0</green>
            <red>0</red>
        </errorBarColor>
        <errorBarEnabled>true</errorBarEnabled>
        <lineWidth>2</lineWidth>
        <name>BEAM:PhotonCam:CenterX</name>
        <pointSize>4</pointSize>
        <pointStyle>NONE</pointStyle>
        <traceColor>
            <blue>255</blue>
            <green>0</green>
            <red>0</red>
        </traceColor>
        <traceType>STEP_HORIZONTALLY</traceType>
        <xAxis>0</xAxis>
        <xErrorBarType>BOTH</xErrorBarType>
        <yAxis>2</yAxis>
        <yErrorBarType>BOTH</yErrorBarType>
    </traceSettingsList>
    <traceSettingsList>
        <antiAliasing>true</antiAliasing>
        <areaAlpha>100</areaAlpha>
        <baseLine>ZERO</baseLine>
        <drawYErrorInArea>true</drawYErrorInArea>
        <errorBarCapWidth>4</errorBarCapWidth>
        <errorBarColor>
            <blue>0</blue>
            <green>0</green>
            <red>255</red>
        </errorBarColor>
        <errorBarEnabled>true</errorBarEnabled>
        <lineWidth>2</lineWidth>
        <name>BEAM:PhotonCam:CenterY</name>
        <pointSize>4</pointSize>
        <pointStyle>NONE</pointStyle>
        <traceColor>
            <blue>0</blue>
            <green>0</green>
            <red>255</red>
        </traceColor>
        <traceType>STEP_HORIZONTALLY</traceType>
        <xAxis>0</xAxis>
        <xErrorBarType>BOTH</xErrorBarType>
        <yAxis>3</yAxis>
        <yErrorBarType>BOTH</yErrorBarType>
    </traceSettingsList>
    <transparent>false</transparent>
</xyGraphSettings>
    <scroll>true</scroll>
    <update_period>3.0</update_period>
    <start>-1 hours -30 minutes 0.0 seconds</start>
    <end>now</end>
    <archive_rescale>STAGGER</archive_rescale>
    <pvlist>
        <pv>
            <name>BEAM:IonChamber</name>
            <visible>true</visible>
            <axis>0</axis>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
            <archive>
                <name>slowcontrol</name>
                <url>jdbc:mysql://slowcontrol.online.a2.kph/archive</url>
                <key>1</key>
            </archive>
        </pv>
        <pv>
            <name>TAGG:TAGG:LadderP2Ratio</name>
            <visible>true</visible>
            <axis>1</axis>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
            <archive>
                <name>slowcontrol</name>
                <url>jdbc:mysql://slowcontrol.online.a2.kph/archive</url>
                <key>1</key>
            </archive>
        </pv>
        <pv>
            <name>BEAM:PhotonCam:CenterX</name>
            <visible>true</visible>
            <axis>2</axis>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
            <archive>
                <name>slowcontrol</name>
                <url>jdbc:mysql://slowcontrol.online.a2.kph/archive</url>
                <key>1</key>
            </archive>
        </pv>
        <pv>
            <name>BEAM:PhotonCam:CenterY</name>
            <visible>true</visible>
            <axis>3</axis>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
            <archive>
                <name>slowcontrol</name>
                <url>jdbc:mysql://slowcontrol.online.a2.kph/archive</url>
                <key>1</key>
            </archive>
        </pv>
    </pvlist>
</databrowser>